### PR TITLE
 Use sqlalchemy scoped_session for thread safety

### PR DESCRIPTION
**Pull request by astrocox**
I've just started running a pipeline that uses `relational_db.Write` with the DataflowRunner as opposed to the local DirectRunner, and I'm getting some errors that seem related to threading. I'm wondering if this could potentially be caused by a single worker with a single instance of `_WriteToRelationalDBFn` [running with multiple threads](https://stackoverflow.com/questions/47777639/google-cloud-dataflow-worker-threading)?

If that is the issue, the SQLAlchemy `scoped_session` seems like a decent option, since it hands out thread-local sessions. These changes seem to fix the issue for me; would it be possible to incorporate this or something similar?

Sample trace, from an error that prevented the row being processed from being written to the DB:
```
File "/usr/local/lib/python2.7/dist-packages/beam_nuggets/io/relational_db.py", line 176, in finish_bundle
    self._db.close_session()
  File "/usr/local/lib/python2.7/dist-packages/beam_nuggets/io/relational_db_api.py", line 259, in close_session
    self._session.close_all()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 65, in close_all
    sess.close()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1268, in close
    self._close_impl(invalidate=False)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1307, in _close_impl
    transaction.close(invalidate)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 581, in close
    self.session.begin()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 922, in begin
    "A transaction is already begun.  Use "
InvalidRequestError: A transaction is already begun.  Use subtransactions=True to allow subtransactions.
```

### CODE REVIEW

**Comment by astrocox** [comment]
Alternatively, since it's not ideal to use a new session for every element in the collection, would it be better to add all the rows in a bundle to a `queue` and write them out once in `finish_bundle()`?

**Comment by mohaseeb** [comment]
Hi @astrocox, as you said, I also think it's not ideal to create a session per element write. 
Since there will be as many concurrent `finish_bundle()`  invocations as threads, I wonder if writing on `finish_bundle()` will solve the issue, since it seems the issue happens somehow when `finish_bundle()` is invoked multiple times?

But I think I don't understand well how beam realizes concurrent  DoFn (_WriteToRelationalDBFn) with multiple threads. So I'd like to reproduce the issue to better understand it; I couldn't though ([I tried this pipeline](https://github.com/mohaseeb/beam-nuggets/blob/reproducing_sqlalchemy_write_threading_issue/examples/dataflow/write_to_relational_db.py) and [with these params](https://github.com/mohaseeb/beam-nuggets/blob/reproducing_sqlalchemy_write_threading_issue/examples/dataflow/write_to_postgresql_gcp_dataflow_runner.sh), it writes 1M records to postgres; the job used 3 instances each with 4 cores).

Can you share how your pipeline looks like? also, does the issue happen randomly?

**Comment by astrocox** [comment]
Thanks for taking a look! I will also see if I can reproduce the issue in a simple/public pipeline. I did some more reading and it looks like beam hasn't had any concurrent processing within a bundle since 1.x.x, so that must not be the actual problem (I'm running with 2.8.0)

**Comment by astrocox** [comment]
It looks like the root of the problem is actually the table creation when it doesn't exist prior to executing the pipeline. That could be a race condition across different bundles. I don't know a ton about Postgres but it [sounds like](https://stackoverflow.com/questions/48041134/postgres-create-table-asynchronously) even though `create_all()` checks if the table exists by default, the table creation is not an atomic transaction. 

Here's the big long stack trace that was hiding under my other session-related errors: ```  File "apache_beam/runners/common.py", line 677, in apache_beam.runners.common.DoFnRunner.process
    self.do_fn_invoker.invoke_process(windowed_value)
  File "apache_beam/runners/common.py", line 414, in apache_beam.runners.common.SimpleInvoker.invoke_process
    windowed_value, self.process_method(windowed_value.value))
  File "/usr/local/lib/python2.7/dist-packages/beam_nuggets/io/relational_db.py", line 173, in process
    self._db.write_record(self.table_config, element)
  File "/usr/local/lib/python2.7/dist-packages/beam_nuggets/io/relational_db_api.py", line 278, in write_record
    table = self._open_table_for_write(table_config, record_dict)
  File "/usr/local/lib/python2.7/dist-packages/beam_nuggets/io/relational_db_api.py", line 307, in _open_table_for_write
    record=record
  File "/usr/local/lib/python2.7/dist-packages/beam_nuggets/io/relational_db_api.py", line 314, in _open_table
    self._get_table(name, get_table_f, **get_table_f_params)
  File "/usr/local/lib/python2.7/dist-packages/beam_nuggets/io/relational_db_api.py", line 320, in _get_table
    table_class = get_table_f(self._session, name, **get_table_f_params)
  File "/usr/local/lib/python2.7/dist-packages/beam_nuggets/io/relational_db_api.py", line 389, in create_table
    metadata.create_all()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/schema.py", line 4201, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2002, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1593, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 130, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 784, in visit_metadata
    _is_metadata_operation=True,
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/visitors.py", line 130, in traverse_single
    return meth(obj, **kw)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 829, in visit_table
    include_foreign_key_constraints,
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 974, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1036, in _execute_ddl
    compiled,
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1234, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1452, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1230, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(analytics_test_5465e62b-7f10-4255-ab5b-2849c0b48100, 2200) already exists.
 [SQL: '\nCREATE TABLE "analytics_test_5465e62b-7f10-4255-ab5b-2849c0b48100" (\n\t"userId" VARCHAR(64) NOT NULL, \n\t"userType" VARCHAR(64) NOT NULL, \n\t"statType" VARCHAR(64) NOT NULL, \n\t"statValue" VARCHAR(64) NOT NULL, \n\t"windowStart" TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\t"windowEnd" TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\t"sourceEventType" VARCHAR(64) NOT NULL, \n\t"statGroup" VARCHAR(64) NOT NULL, \n\tCONSTRAINT "analytics_test_5465e62b-7f10-4255-ab5b-2849c0b48100_pk" PRIMARY KEY ("userId", "userType", "statType", "statValue", "statGroup", "windowStart", "windowEnd", "sourceEventType")\n)\n\n'] (Background on this error at: http://sqlalche.me/e/gkpj)```

**Pull request closed without merging**
